import { notFound } from "next/navigation";

import {
  approveSolutionPlanAction,
  createContractPackageAction,
  createDeliveryProjectAction,
  createProposalAction,
} from "@/lib/actions/delivery";
import { requireAppPermission } from "@/lib/auth/guard";
import { getSolutionPlan } from "@/lib/delivery/engine";
import { can } from "@/lib/rbac/permissions";
import { ActionForm } from "../../_components/action-form";
import { Card, Field, PageHeader, PageShell, PrimaryButton, formatLabel, inputClassName } from "../../_components/ui";
import { StatusBadge } from "@/components/ui/display";

export default async function SolutionPlanPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const principal = await requireAppPermission("solutions.read");
  const { id } = await params;
  const row = await getSolutionPlan(id, principal.organizationId);
  if (!row) notFound();
  const { plan } = row;

  return (
    <PageShell>
      <PageHeader
        eyebrow="Solutions"
        title={plan.title}
        description={`${row.companyName} · ${row.serviceName} · version ${row.version}`}
        metadata={
          <StatusBadge tone={plan.status === "approved" ? "success" : "navy"}>
            {formatLabel(plan.status)}
          </StatusBadge>
        }
      />
      <div className="mt-6 grid gap-4 md:grid-cols-2">
        {[
          ["Problem", plan.problemStatement],
          ["Business impact", plan.businessImpact],
          ["Scope", plan.recommendedScope],
          ["Deliverables", plan.deliverables],
          ["Timeline", plan.timeline],
          ["KPIs", plan.kpis],
          ["Pricing", `${plan.pricingModel ?? ""} ${plan.approvedPrice ?? plan.recommendedPrice ?? ""}`],
          ["Expansion", plan.expansionOpportunities],
        ].map(([label, value]) => (
          <Card key={label}>
            <p className="eyebrow">{label}</p>
            <p className="mt-2 whitespace-pre-wrap text-sm">{value || "—"}</p>
          </Card>
        ))}
      </div>
      <p className="mt-4 text-xs text-muted-foreground">
        Generated by {plan.generatedByModel ?? "human"} {plan.generatedByModelVersion ?? ""} · not client-facing until approved.
      </p>
      <div className="mt-8 flex flex-wrap gap-4">
        {can(principal, "solutions.approve") && plan.status !== "approved" ? (
          <ActionForm action={approveSolutionPlanAction}>
            <input type="hidden" name="solutionPlanId" value={plan.id} />
            <PrimaryButton>Approve plan</PrimaryButton>
          </ActionForm>
        ) : null}
        {can(principal, "proposals.write") && plan.status === "approved" ? (
          <ActionForm action={createProposalAction}>
            <input type="hidden" name="solutionPlanId" value={plan.id} />
            <PrimaryButton>Generate proposal</PrimaryButton>
          </ActionForm>
        ) : null}
        {can(principal, "contracts.write") && plan.companyId ? (
          <ActionForm action={createContractPackageAction}>
            <input type="hidden" name="serviceCode" value={row.serviceCode} />
            <input type="hidden" name="companyId" value={plan.companyId} />
            <input type="hidden" name="opportunityId" value={plan.opportunityId} />
            <input type="hidden" name="solutionPlanId" value={plan.id} />
            <button className="rounded-full border px-4 py-2 text-sm" type="submit">
              Create contract package
            </button>
          </ActionForm>
        ) : null}
      </div>
      {can(principal, "projects.write") && plan.status === "approved" ? (
        <ActionForm action={createDeliveryProjectAction} className="mt-6 max-w-xl space-y-3">
          <input type="hidden" name="solutionPlanId" value={plan.id} />
          <Field label="Executed contract id (optional)" name="contractId">
            <input className={inputClassName} id="contractId" name="contractId" />
          </Field>
          <Field label="Managing Partner override reason" name="overrideReason">
            <input className={inputClassName} id="overrideReason" name="overrideReason" />
          </Field>
          <PrimaryButton>Create delivery project</PrimaryButton>
        </ActionForm>
      ) : null}
    </PageShell>
  );
}
