import { notFound } from "next/navigation";

import { approveSolutionPlanAction, createProposalAction } from "@/lib/actions/delivery";
import { AcademyHelp } from "@/components/academy/academy-help";
import { ConceptNote } from "@/components/ia/concept-note";
import { ButtonLink } from "@/components/ui/button";
import { requireAppPermission } from "@/lib/auth/guard";
import { canBuildProposalFromPlan, inFlightProposal } from "@/lib/delivery/commercial-path";
import { getSolutionPlan, listOpportunityCommercialPath } from "@/lib/delivery/engine";
import { can } from "@/lib/rbac/permissions";
import { ActionForm } from "../../_components/action-form";
import { Card, PageHeader, PageShell, PrimaryButton, formatLabel } from "../../_components/ui";
import { StatusBadge } from "@/components/ui/display";

export default async function SolutionPlanPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const principal = await requireAppPermission("solutions.read");
  const { id } = await params;
  const row = await getSolutionPlan(id, principal.organizationId);
  if (!row) notFound();
  const { plan } = row;
  const commercial = await listOpportunityCommercialPath(principal.organizationId, plan.opportunityId);
  const inflight = inFlightProposal(commercial);
  const showApprove = can(principal, "solutions.approve") && plan.status !== "approved";
  const showBuild = can(principal, "proposals.write") && canBuildProposalFromPlan(commercial, plan.status);
  const showOpenProposal = Boolean(inflight);

  return (
    <PageShell>
      <PageHeader
        eyebrow="Solutions"
        title={plan.title}
        description={`${row.companyName} · ${row.serviceName} · version ${row.version}`}
        metadata={
          <StatusBadge tone={plan.status === "approved" ? "success" : "navy"}>
            {formatLabel(plan.status)}
          </StatusBadge>
        }
        actions={<AcademyHelp articleSlug="module-proposals" />}
      />
      <ConceptNote concept="solutionVsProposalVsSow" />
      <div className="mt-6 grid gap-4 md:grid-cols-2">
        {[
          ["Problem", plan.problemStatement],
          ["Business impact", plan.businessImpact],
          ["Scope", plan.recommendedScope],
          ["Deliverables", plan.deliverables],
          ["Timeline", plan.timeline],
          ["KPIs", plan.kpis],
          ["Pricing", `${plan.pricingModel ?? ""} ${plan.approvedPrice ?? plan.recommendedPrice ?? ""}`],
          ["Expansion", plan.expansionOpportunities],
        ].map(([label, value]) => (
          <Card key={label}>
            <p className="eyebrow">{label}</p>
            <p className="mt-2 whitespace-pre-wrap text-sm">{value || "—"}</p>
          </Card>
        ))}
      </div>
      <p className="mt-4 text-xs text-muted-foreground">
        Generated by {plan.generatedByModel ?? "human"} {plan.generatedByModelVersion ?? ""} · not client-facing until approved.
      </p>
      <div className="mt-8 flex flex-wrap gap-4">
        {showApprove ? (
          <ActionForm action={approveSolutionPlanAction}>
            <input type="hidden" name="solutionPlanId" value={plan.id} />
            <PrimaryButton>Approve plan</PrimaryButton>
          </ActionForm>
        ) : null}
        {showBuild ? (
          <ActionForm action={createProposalAction}>
            <input type="hidden" name="solutionPlanId" value={plan.id} />
            <PrimaryButton>Build proposal</PrimaryButton>
          </ActionForm>
        ) : null}
        {showOpenProposal && inflight ? (
          <ButtonLink href={`/app/proposals/${inflight.id}`} variant="primary">
            Open proposal
          </ButtonLink>
        ) : null}
      </div>
      <p className="mt-3 text-sm text-muted-foreground">
        Contract / SOW and delivery project come after the client accepts the proposal. Do not build a second proposal from this plan while one is in flight.
      </p>
    </PageShell>
  );
}
