import type { Permission } from "@/lib/rbac/permissions";
import { ACCESS_BUNDLE_LABELS, ROLE_GUIDE } from "@/lib/rbac/role-guide";
import type { RoleSlug } from "@/lib/rbac/permissions";
import { SCOUT_COMMAND_FAMILIES, type ScoutCommandFamily } from "@/lib/scout/commands";

import type { AcademyArticle, AcademySectionId } from "./types";

const ALL_SCOUT = [...SCOUT_COMMAND_FAMILIES];

function article(input: AcademyArticle): AcademyArticle {
  return input;
}

function accessQuickStart(slug: RoleSlug): AcademyArticle {
  const guide = ROLE_GUIDE[slug];
  return article({
    slug: `access-${slug}`,
    title: `${ACCESS_BUNDLE_LABELS[slug]} access`,
    section: "access-quick-starts",
    summary: `${ACCESS_BUNDLE_LABELS[slug]} is an access bundle, not a job title. ${guide.access}`,
    sources: [
      "docs/business/PIERONE_OPERATING_MANUAL.md",
      "lib/rbac/role-guide.ts",
      "lib/rbac/permissions.ts",
    ],
    purpose: `Explain what the ${ACCESS_BUNDLE_LABELS[slug]} bundle can open and what it cannot.`,
    whenToUse: "When you are assigned this bundle, or when you assign it to someone else in People.",
    whoUsesIt: guide.audience,
    accessRequired: ["knowledge.read"],
    screenOverview: [
      { href: "/app/admin/users", label: "People" },
      { href: "/app/admin/roles", label: "Access bundles" },
    ],
    stepByStep: [
      "Title ≠ Access (DEC-AUTH-002). Organizational title on People is display-only.",
      `${guide.access}`,
      "Effective access is the union of assigned bundles, then grant/deny overrides (deny wins).",
      "Cite docs/business/PIERONE_OPERATING_MANUAL.md — Title ≠ Access.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD"],
    approvalRequirements: "Changing bundles requires admin.users / admin.roles. Completing this article does not grant the bundle.",
    relatedSlugs: ["access-quick-start", "admin", "module-admin-people"],
    commonMistakes: [
      "Treating the bundle name as a job title.",
      "Expecting a title change in People to open new screens.",
    ],
    troubleshooting: [
      "Missing a screen? Check effective permissions on the person record, not the title field.",
    ],
  });
}

function playbookArticle(input: {
  slug: string;
  title: string;
  file: string;
  summary: string;
  screens: AcademyArticle["screenOverview"];
  accessRequired: Permission[];
  relatedSlugs: string[];
}): AcademyArticle {
  return article({
    slug: input.slug,
    title: input.title,
    section: "service-playbooks",
    summary: input.summary,
    sources: [`docs/business/playbooks/${input.file}`, "docs/business/SERVICE_PLAYBOOKS.md"],
    purpose: `Surface the approved ${input.title} playbook. Academy is not a second source of truth.`,
    whenToUse: "When you are assigned this delivery work and need the screen / owner / approval map.",
    whoUsesIt: "Operators with the access listed in the playbook — by bundle, not by job title.",
    accessRequired: input.accessRequired,
    screenOverview: input.screens,
    stepByStep: [
      `Follow docs/business/playbooks/${input.file}. Each step already maps WorkforceOS screen, data, owner, permission, approval, Scout command, deliverable, and next step.`,
      "Do not invent workflow or military-mapping rules here. Load approved service_workflows when you execute.",
      "Scout send is still denied. Humans send.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD"],
    approvalRequirements: "Human approval stays required where the playbook says so. Agents cannot approve their own material output.",
    relatedSlugs: input.relatedSlugs,
    commonMistakes: [
      "Treating this Academy article as a replacement for the playbook or workflow record.",
      "Inventing a sixth launch service.",
    ],
    troubleshooting: [
      "If a URL is listed as not live in the playbook README, use the listed live screen instead.",
    ],
  });
}

export const ACADEMY_ARTICLES: AcademyArticle[] = [
  article({
    slug: "getting-started",
    title: "Getting started in WorkforceOS",
    section: "getting-started",
    summary: "What PierOne does, what you are allowed to do, and where Help & Training lives.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/business/SERVICE_CATALOG.md"],
    isTrainingModule: true,
    requiredIfAny: [],
    contextualRoutes: ["/app"],
    purpose: "Give a new operator the company model, five offers, and the Help & Training path without tribal knowledge.",
    whenToUse: "Day one, and whenever you are assigned a new access bundle.",
    whoUsesIt: "Every signed-in PierOne employee.",
    accessRequired: ["scout.use"],
    screenOverview: [
      { href: "/app", label: "Command Center" },
      { href: "/app/academy", label: "Help & Training (Academy)" },
    ],
    stepByStep: [
      "PierOne Partners is a Workforce & Talent Solutions firm. We are not a temp staffing agency, payroll company, public job marketplace, or SkillBridge host (PIERONE_OPERATING_MANUAL.md).",
      "Every engagement follows SOLVE → BUILD → OPERATE.",
      "Five launch services only: Professional Search, Military Talent Opportunity Assessment, Talent Acquisition Performance Assessment, Fractional Talent Partner, Workforce Pipeline Assessment.",
      "Access comes from PostgreSQL access bundles, not job title (DEC-AUTH-002).",
      "Open required training on this Academy home. Completion does not raise permissions.",
      "New PierOne employees use Staff onboarding at /app/academy/onboarding. That is not the ATS hire queue at /app/onboarding.",
      "Scout is the persistent assistant (tooltip: Open Scout). Chat is not the system of record. Scout never generates SQL and cannot send externally yet.",
    ],
    scoutCommands: ["SEARCH", "SHOW_DASHBOARD"],
    approvalRequirements: "None to read Academy. Material client-facing AI still needs a human.",
    relatedSlugs: ["employee-onboarding", "operating-model", "access-quick-start", "scout", "security-candidate-privacy"],
    commonMistakes: [
      "Asking Scout to invent process that is not in an approved playbook.",
      "Assuming a title on People opens screens.",
    ],
    troubleshooting: [
      "Cannot open a module? You lack the permission — ask an administrator to assign a bundle, not a title.",
    ],
  }),
  article({
    slug: "operating-model",
    title: "PierOne operating model",
    section: "operating-model",
    summary: "SOLVE → BUILD → OPERATE, the five offers, and the three canonical flows.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    isTrainingModule: true,
    requiredIfAny: [],
    purpose: "Map how PierOne runs work in WorkforceOS. This article cites the company manual; it does not replace it.",
    whenToUse: "Before you own a client, search, military, or delivery step.",
    whoUsesIt: "Every operator.",
    accessRequired: ["scout.use"],
    screenOverview: [
      { href: "/app/services", label: "Service Catalog" },
      { href: "/app/crm/inquiries", label: "Website inquiries" },
      { href: "/app/jobs", label: "Jobs" },
      { href: "/app/military", label: "Military Talent" },
    ],
    stepByStep: [
      "Read docs/business/PIERONE_OPERATING_MANUAL.md for the locked client, recruiting, and military flows.",
      "Client: Website Inquiry → CRM → Qualification → Discovery → Solution → Proposal → Contract → Project → Delivery → Reporting → Invoice → Expansion.",
      "Recruiting: Job → Candidate → Application → Screening → Matching → Client Submission → Interview → Offer → Hire → Onboarding. Internal Talent Network before external sourcing.",
      "Military (DEC-MIL-005): Transitioning Service Member → Military Talent Network → Transition Talent Profile → Skills Translation → Employer Opportunity → Match → Employer Engagement → Interview → SkillBridge / Direct Hire / Other → Placement → Conversion.",
      "Public site may say Professional & Technical Search — same offer as Professional Search, not a rename.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD"],
    approvalRequirements: "Workflow steps that require human approval stay in the approved service_workflows records.",
    relatedSlugs: ["getting-started", "playbook-professional-search", "military-talent"],
    commonMistakes: [
      "Inventing a sixth service.",
      "Treating SkillBridge as a PierOne-owned program.",
    ],
    troubleshooting: [
      "Qualification, expansion, screening, and matching have no dedicated routes — use the live screens listed in the manual.",
    ],
  }),
  article({
    slug: "employee-onboarding",
    title: "Employee onboarding",
    section: "getting-started",
    summary: "PierOne staff path from Admin invite to Week 4 access/training review. Not the ATS hire queue.",
    sources: [
      "docs/business/PIERONE_OPERATING_MANUAL.md",
      "docs/operations/MASTER_COMPLETION_LEDGER.md",
      "lib/staff-onboarding/cadence.ts",
    ],
    contextualRoutes: ["/app/academy/onboarding"],
    purpose: "Give a new PierOne employee a repeatable Day 1–Week 4 path without merging it into candidate hire onboarding.",
    whenToUse: "When a person is invited in People, or when you are a new PierOne employee.",
    whoUsesIt: "Every new PierOne employee; People administrators manage someone else’s cadence.",
    accessRequired: ["scout.use"],
    screenOverview: [
      { href: "/app/academy/onboarding", label: "Staff onboarding (your checklist)" },
      { href: "/app/admin/users", label: "People" },
      { href: "/app/onboarding", label: "ATS hire onboarding", note: "Different product — client/candidate new-hire tasks" },
    ],
    fields: [
      { name: "Organizational title", notes: "Display only. Title ≠ Access (DEC-AUTH-002)." },
      { name: "Manager", notes: "users.manager_id. Nullable. A person cannot be their own manager." },
      { name: "Access bundles", notes: "Assigned in People. Required training follows effective access, not title." },
      { name: "Systems / equipment", notes: "Laptop, Clerk login, email, WorkforceOS access. Stored checklist, not procurement." },
      { name: "Policy acknowledgements", notes: "Security & Candidate Privacy, timestamped. Not a legal CMS." },
    ],
    stepByStep: [
      "Admin invites the person in People and assigns a starting access bundle. A staff_onboarding record starts at Day 1. This is not /app/onboarding (ATS).",
      "Day 1: Company + Security + WorkforceOS Basics — Academy Getting Started, Operating Model, and Security. Complete the systems checklist and Security & Candidate Privacy acknowledgement.",
      "Week 1: Access-specific workflows from TRAINING_REQUIREMENT_MAP. Recruiter Standard still has no opportunities.read. Military Talent Partner is the live military bundle.",
      "Week 2: Shadow / practice cases. Tracked as state, not a calendar invite.",
      "Week 3: Supervised production work. Still no permission auto-grant.",
      "Week 4: A People administrator records an access/training review. Completing Academy or this review does not assign bundles or overrides.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "Week 4 review is a human People-admin action. Agents cannot approve access. Training completion is not an approval.",
    relatedSlugs: ["getting-started", "operating-model", "security-candidate-privacy", "access-quick-start", "admin"],
    commonMistakes: [
      "Opening Talent → Onboarding for a PierOne employee. That queue is ATS client-hire tasks.",
      "Expecting required Academy modules to raise permissions.",
      "Setting a person as their own manager.",
    ],
    troubleshooting: [
      "Missing a required Week 1 module? Check effective permissions on the People record, not title.",
      "Need the article in Scout? SEARCH Academy for employee onboarding. Scout cannot send and never generates SQL.",
    ],
  }),
  article({
    slug: "access-quick-start",
    title: "Title ≠ Access",
    section: "access-quick-starts",
    summary: "Organizational title is display-only. Access bundles grant permissions.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/decisions/DECISION_LOG.md"],
    isTrainingModule: true,
    requiredIfAny: [],
    contextualRoutes: ["/app/admin/users"],
    purpose: "Stop operators from treating job title as authorization (DEC-AUTH-002).",
    whenToUse: "When someone cannot open a screen, or when you assign People access.",
    whoUsesIt: "Every employee; People administrators assign bundles.",
    accessRequired: ["scout.use"],
    screenOverview: [
      { href: "/app/admin/users", label: "People" },
      { href: "/app/admin/roles", label: "Access bundles" },
      { href: "/app/admin/access-review", label: "Access review" },
    ],
    stepByStep: [
      "Clerk authenticates. Local PostgreSQL users, roles, and user_roles authorize.",
      "A person may hold zero or more access bundles. Overrides are grant or deny; deny wins.",
      "Recruiter Standard does not own commercial opportunities (DEC-RBAC-001) — no opportunities.read on that bundle.",
      "Military Talent Partner is the live military bundle. Do not write Military Talent Specialist in operator copy.",
      "Completing Academy training never auto-increases permissions.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD"],
    approvalRequirements: "Bundle changes are an admin action. Title edits are not.",
    relatedSlugs: [
      "access-recruiter",
      "access-military-talent-partner",
      "access-talent-partner",
      "module-admin-people",
    ],
    commonMistakes: [
      "Changing Title on People and expecting new screens.",
      "Giving recruiters agents.manage so they can see AI costs.",
    ],
    troubleshooting: [
      "Open the person record and read Effective permissions. That set is the authorization input.",
    ],
  }),
  accessQuickStart("managing-partner"),
  accessQuickStart("operations-administrator"),
  accessQuickStart("strategy-technology-administrator"),
  accessQuickStart("talent-partner"),
  accessQuickStart("recruiter"),
  accessQuickStart("workforce-consultant"),
  accessQuickStart("military-talent-partner"),
  accessQuickStart("read-only"),
  article({
    slug: "module-command-center",
    title: "Command Center",
    section: "user-manual",
    summary: "Live snapshot of stored operating records — not projections.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    contextualRoutes: ["/app"],
    purpose: "Show what the Command Center is for and which counts you will see.",
    whenToUse: "Start of day, leadership reviews, or when you need a stored-data snapshot.",
    whoUsesIt: "Anyone who can sign in. Cards hide when you lack the module permission.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app", label: "Command Center" }],
    fields: [
      { name: "Contracted / invoiced / collected / AR / MRR", notes: "Shown only with finance.read. Values come from stored finance rows." },
      { name: "Pipeline / discovery / proposals", notes: "Shown only with opportunities.read." },
      { name: "Active searches", notes: "Shown only with jobs.read." },
    ],
    stepByStep: [
      "Open /app. Figures come from saved data, not forecasts.",
      "Weekly operating reviews use the Leadership / Operations / Talent / Military Talent / Finance / GTM tabs on the same page.",
      "Follow a card into the live module. Do not treat chat as the record.",
      "Cite PIERONE_OPERATING_MANUAL.md Reporting step and leadership cadence.",
    ],
    scoutCommands: ["SHOW_DASHBOARD", "SEARCH", "SUMMARIZE"],
    approvalRequirements: "None to view authorized cards. Approvals remain on their source records.",
    relatedSlugs: ["getting-started", "weekly-operating-review", "ninety-day-gtm-review", "finance", "recruiting-hiring"],
    commonMistakes: ["Treating dashboard numbers as projections."],
    troubleshooting: ["A missing card usually means you do not have that module's read permission."],
  }),
  article({
    slug: "weekly-operating-review",
    title: "Weekly operating review",
    section: "user-manual",
    summary: "Run Leadership, Operations, Talent, Military Talent, Finance, and GTM reviews from Command Center using live aggregates.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/decisions/DECISION_LOG.md"],
    contextualRoutes: ["/app?cadence=leadership", "/app?cadence=operations", "/app?cadence=talent", "/app?cadence=military", "/app?cadence=finance", "/app?cadence=gtm"],
    purpose: "Show where PierOne management cadence lives in WorkforceOS instead of a slide deck.",
    whenToUse: "Weekly pipeline review, delivery standup, talent aging, Military Talent operations, or operating-finance AR.",
    whoUsesIt: "Operators with the matching read permission. Title is not access.",
    accessRequired: ["scout.use"],
    screenOverview: [
      { href: "/app?cadence=leadership", label: "Leadership review" },
      { href: "/app?cadence=operations", label: "Operations review" },
      { href: "/app?cadence=talent", label: "Talent review" },
      { href: "/app?cadence=military", label: "Military Talent review" },
      { href: "/app?cadence=finance", label: "Finance review" },
      { href: "/app?cadence=gtm", label: "GTM review" },
      { href: "/app/alerts", label: "Alerts" },
      { href: "/app/reports", label: "Reports" },
    ],
    stepByStep: [
      "Open Command Center /app and pick a cadence tab. Boards are review groups, not extra nav items.",
      "Each widget is a business question, a live PostgreSQL count, a short exception list, and a link to the operating screen. Missing values stay empty.",
      "Recruiter Standard does not see the commercial opportunity pipeline (DEC-RBAC-001). Military Talent Partner language stays intermediary. SkillBridge is a pathway type, not a PierOne-owned program.",
      "Risks are derived from stale opportunities, overdue deliverables, past-due AR, and failed integrations. There is no fake risk register.",
      "Ask Scout: weekly operating review. Scout repeats counts you can already read. It does not generate SQL, does not send, and does not put candidate email, phone, compensation, or resume in model context. Humans still own decisions.",
      "Alerts stay on /app/alerts (DEC-OPS-002). Finance is operational AR, not a general ledger (DEC-FIN-002).",
    ],
    scoutCommands: ["SHOW_DASHBOARD", "SUMMARIZE", "SEARCH"],
    approvalRequirements: "Scout cannot approve material output. Weekly counts are read-only.",
    relatedSlugs: ["module-command-center", "ninety-day-gtm-review", "operating-model", "military-talent", "finance"],
    commonMistakes: [
      "Treating Command Center as a BI builder.",
      "Calling SkillBridge a PierOne-owned host program.",
      "Expecting a title change to open a cadence tab.",
    ],
    troubleshooting: [
      "Missing Leadership pipeline cards? You lack opportunities.read.",
      "Missing Finance? You lack finance.read.",
      "Missing GTM? You lack opportunities.read. Recruiter Standard cannot see the commercial GTM board.",
    ],
  }),
  article({
    slug: "ninety-day-gtm-review",
    title: "90-day GTM review",
    section: "user-manual",
    summary: "Run the weekly 90-day GTM review from Command Center against the written PierOne plan, target-account tiers, and live conversion counts.",
    sources: [
      "docs/business/PIERONE_90_DAY_GTM_PLAN.md",
      "docs/business/PIERONE_OPERATING_MANUAL.md",
      "docs/business/SERVICE_PLAYBOOKS.md",
    ],
    contextualRoutes: ["/app?cadence=gtm", "/app/companies", "/app/opportunities", "/app/crm/inquiries", "/app/public-content"],
    purpose: "Show where the 90-day GTM plan is executed in WorkforceOS instead of a second CRM or a slide deck.",
    whenToUse: "Weekly GTM review, target-account classification, Southeast outbound, inquiry qualification, or proposal conversion.",
    whoUsesIt: "Managing Partner, Senior Talent Partner, Operations, and other bundles with opportunities.read. Title is not access.",
    accessRequired: ["opportunities.read"],
    screenOverview: [
      { href: "/app?cadence=gtm", label: "GTM review" },
      { href: "/app/companies", label: "Companies" },
      { href: "/app/opportunities", label: "Opportunities" },
      { href: "/app/discovery", label: "Discovery" },
      { href: "/app/proposals", label: "Proposals" },
      { href: "/app/crm/inquiries", label: "Website inquiries" },
      { href: "/app/public-content", label: "Public Content" },
    ],
    fields: [
      { name: "gtm_tier", notes: "Tier 1 or Tier 2 on Companies. Locked focus industries are not new services." },
      { name: "gtm_region", notes: "Southeast BD vs national recruiting." },
    ],
    stepByStep: [
      "Cite docs/business/PIERONE_90_DAY_GTM_PLAN.md. Five launch services only. Inquiries are intake, not auto-opportunities (DEC-WEB-004).",
      "Open /app?cadence=gtm. Recruiter Standard does not see this board (DEC-RBAC-001). Title is not access (DEC-AUTH-002).",
      "Classify target accounts on /app/companies with industry, gtm_tier, and gtm_region. Do not invent a parallel accounts table.",
      "Southeast BD stores next actions on the company or activity. Overdue follow-ups are derived from those dates — this is not a sequencer product.",
      "Military employer conversations stay intermediary. SkillBridge is a pathway type, not a PierOne-owned program. Use Military Talent Partner language.",
      "Thought leadership is Public Content /app/public-content (DEC-WEB-010). Do not rebuild a CMS.",
      "Ask Scout: weekly GTM review. Scout repeats counts you can already read. It does not generate SQL, does not send, and does not put candidate email, phone, compensation, or resume in model context.",
    ],
    scoutCommands: ["SHOW_DASHBOARD", "SEARCH", "SUMMARIZE"],
    approvalRequirements: "Scout cannot approve material output. Proposals still need internal review before send.",
    relatedSlugs: ["weekly-operating-review", "module-companies", "module-opportunities", "playbook-client-discovery"],
    commonMistakes: [
      "Treating a website inquiry as an opportunity.",
      "Expecting Recruiter Standard to see the GTM pipeline.",
      "Adding a sixth launch service or a temp-staffing offer.",
    ],
    troubleshooting: [
      "Missing the GTM tab? You lack opportunities.read.",
      "Empty target-account count? Set gtm_tier on Companies.",
    ],
  }),
  article({
    slug: "module-companies",
    title: "Companies",
    section: "user-manual",
    summary: "Prospect and client company records. Operating size is not ownership data.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "db/schema/crm/index.ts"],
    contextualRoutes: ["/app/companies"],
    purpose: "Find and maintain company CRM records.",
    whenToUse: "When a website inquiry, opportunity, or delivery project needs a company.",
    whoUsesIt: "Commercial owners and recruiters who can read companies.",
    accessRequired: ["companies.read"],
    screenOverview: [
      { href: "/app/companies", label: "Companies" },
      { href: "/app/contacts", label: "Contacts" },
    ],
    fields: [
      { name: "name", notes: "Required company name (list column Name)." },
      { name: "companyType", notes: "List column Type." },
      { name: "clientStatus", notes: "List column Status." },
      { name: "industry", notes: "List column Industry." },
      { name: "gtm_tier", notes: "Optional 90-day target-account tier (Tier 1 / Tier 2)." },
      { name: "gtm_region", notes: "Optional Southeast BD vs national recruiting." },
    ],
    stepByStep: [
      "Search by name on /app/companies.",
      "Open the company for locations, contacts, opportunities, and finance tabs.",
      "There is no /app/expansion route — expansion suggestions live on the company solutions tab after closeout.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD", "CREATE", "UPDATE"],
    approvalRequirements: "Creating or editing a company is companies.write. Opportunities are not auto-created from inquiries.",
    relatedSlugs: ["module-opportunities", "playbook-client-discovery"],
    commonMistakes: ["Storing ownership percentages. Cap-table data is forbidden."],
    troubleshooting: ["Recruiters can read companies/contacts but do not own the commercial opportunity list."],
  }),
  article({
    slug: "module-opportunities",
    title: "Opportunities",
    section: "user-manual",
    summary: "Commercial opportunities on the SOLVE → BUILD spine.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    contextualRoutes: ["/app/opportunities"],
    purpose: "Track sellable work for one of the five launch services.",
    whenToUse: "After a website inquiry is qualified, or when expanding an existing client.",
    whoUsesIt: "Senior Talent Partner, Operations, Workforce Consultant, Strategy & Technology, Administrator / Executive.",
    accessRequired: ["opportunities.read"],
    screenOverview: [
      { href: "/app/opportunities", label: "Opportunities" },
      { href: "/app/crm/inquiries", label: "Website inquiries" },
    ],
    stepByStep: [
      "Recruiter Standard cannot open this list (DEC-RBAC-001).",
      "Convert a qualified inquiry from /app/crm/inquiries/[id] — an inquiry is not an opportunity.",
      "Do not invent a service code outside the five launch offers.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD", "CREATE", "UPDATE", "ASSIGN"],
    approvalRequirements: "opportunities.write to create or advance. Human conversion from inquiry.",
    relatedSlugs: ["module-discovery", "proposals", "access-recruiter"],
    commonMistakes: ["Auto-creating opportunities from the public website."],
    troubleshooting: ["If you cannot see Opportunities, you do not have opportunities.read — a title will not fix that."],
  }),
  article({
    slug: "module-discovery",
    title: "Discovery",
    section: "user-manual",
    summary: "Structured discovery against the approved service workflow.",
    sources: ["docs/business/playbooks/client-discovery.md"],
    contextualRoutes: ["/app/discovery"],
    purpose: "Capture required discovery inputs from the approved workflow, not a free-form form.",
    whenToUse: "Once an opportunity exists and you are designing the offer.",
    whoUsesIt: "Operators with discovery.read / discovery.write.",
    accessRequired: ["discovery.read"],
    screenOverview: [
      { href: "/app/discovery", label: "Discovery" },
      { href: "/app/solutions", label: "Solution Plans" },
    ],
    stepByStep: [
      "Open /app/discovery or /app/discovery/[id].",
      "Required questions come from the approved service workflow — do not invent extra process rules.",
      "Cite playbooks/client-discovery.md for the step map.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "CREATE_TASK", "CREATE_FOLLOW_UP", "DRAFT"],
    approvalRequirements: "Discovery notes are operator work. Client-facing findings later need solution or deliverable approval.",
    relatedSlugs: ["playbook-client-discovery", "operating-model"],
    commonMistakes: ["Skipping the approved workflow inputs."],
    troubleshooting: ["Create discovery from an existing opportunity, not from a raw inquiry."],
  }),
  article({
    slug: "module-proposals",
    title: "Proposals module",
    section: "user-manual",
    summary: "Proposals are generated from approved solution plans.",
    sources: ["docs/business/playbooks/proposal-contract-handoff.md"],
    contextualRoutes: ["/app/proposals"],
    purpose: "Move an approved solution to a reviewable proposal.",
    whenToUse: "After solutions.approve, before contract.",
    whoUsesIt: "Operators with proposals.read. Write/approve is a tighter set.",
    accessRequired: ["proposals.read"],
    screenOverview: [
      { href: "/app/proposals", label: "Proposals" },
      { href: "/app/solutions", label: "Solution Plans" },
    ],
    fields: [
      { name: "title", notes: "List column Proposal." },
      { name: "status", notes: "List column Status. Send is blocked until approved." },
    ],
    stepByStep: [
      "Generate from an approved solution plan.",
      "Path is draft → internal_review → proposals.approve → human send.",
      "Scout cannot send. Cite playbooks/proposal-contract-handoff.md.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD", "DRAFT"],
    approvalRequirements: "proposals.approve before send. Pricing outside range needs pricing.approve.",
    relatedSlugs: ["proposals", "contracts", "ai-use-human-review"],
    commonMistakes: ["Sending a draft proposal from Scout."],
    troubleshooting: ["No proposal? The solution plan is not approved yet."],
  }),
  article({
    slug: "module-jobs",
    title: "Jobs",
    section: "user-manual",
    summary: "Recruiting entry. Search the Talent Network before external sourcing.",
    sources: ["docs/business/playbooks/recruiting-and-hiring.md"],
    contextualRoutes: ["/app/jobs"],
    purpose: "Run search assignments on one job surface.",
    whenToUse: "When Professional Search or hiring execution starts.",
    whoUsesIt: "Recruiter Standard, Senior Talent Partner, Military Talent Partner.",
    accessRequired: ["jobs.read"],
    screenOverview: [
      { href: "/app/jobs", label: "Jobs" },
      { href: "/app/talent", label: "Candidates" },
      { href: "/app/pipeline", label: "Candidate Pipeline" },
    ],
    fields: [
      { name: "title", notes: "List column Title." },
      { name: "locationLabel", notes: "List column Location." },
      { name: "status", notes: "List column Status." },
      { name: "priority", notes: "List column Priority." },
    ],
    stepByStep: [
      "Jobs is the recruiting entry. Older requisition/search-project URLs resolve here.",
      "Mark internal Talent Network search complete before any external sourcing hook (WFOS-TAL-002).",
      "Cite playbooks/recruiting-and-hiring.md and playbooks/professional-search.md.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD", "FIND_MATCHES", "ADD_TO_JOB", "CREATE", "UPDATE"],
    approvalRequirements: "jobs.approve / jobs.publish for public postings. Public postings omit confidential client identity.",
    relatedSlugs: ["recruiting-hiring", "module-talent"],
    commonMistakes: ["Sourcing externally before the internal search is complete.", "Duplicating a candidate per job."],
    troubleshooting: ["There is no /app/matching route — use the job and /app/jobs/[id]/pipeline."],
  }),
  article({
    slug: "module-talent",
    title: "Talent Network",
    section: "user-manual",
    summary: "One permanent candidate record. Restricted PII needs candidate_pii.read.",
    sources: [".cursor/rules/security.mdc", "docs/business/PIERONE_OPERATING_MANUAL.md"],
    contextualRoutes: ["/app/talent"],
    purpose: "Find and maintain the single person record used across jobs and Military Talent.",
    whenToUse: "Any search, military pathway, or hiring step that names a person.",
    whoUsesIt: "Operators with candidates.read. Email/phone/compensation/resume need candidate_pii.read.",
    accessRequired: ["candidates.read"],
    screenOverview: [
      { href: "/app/talent", label: "Candidates" },
      { href: "/app/talent/search", label: "Talent Search" },
      { href: "/app/talent/pools", label: "Talent Pools" },
    ],
    fields: [
      { name: "fullName", notes: "List column Name." },
      { name: "currentTitle", notes: "List column Title." },
      { name: "availability", notes: "List column Availability." },
      { name: "email", notes: "Restricted PII. Hidden without candidate_pii.read." },
    ],
    stepByStep: [
      "Never duplicate a candidate per requisition or employer.",
      "SkillBridge people are existing Talent Network candidates with a Transition Talent Profile overlay.",
      "Scout strips email, phone, compensation, and resume before any model context.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD", "ADD_TO_POOL", "ADD_TO_JOB"],
    approvalRequirements: "Privacy deletion is a separate controlled process. Ordinary archive is not deletion.",
    relatedSlugs: ["security-candidate-privacy", "military-talent", "recruiting-hiring"],
    commonMistakes: ["Creating a second person because they applied again.", "Pasting resume text into Scout."],
    troubleshooting: ["Missing email on the list? You do not have candidate_pii.read."],
  }),
  article({
    slug: "module-military",
    title: "Military Talent screens",
    section: "user-manual",
    summary: "Intermediary model, Transition Talent Profile, SkillBridge-eligible pathway.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/business/playbooks/military-transition-pathway.md"],
    contextualRoutes: ["/app/military"],
    purpose: "Operate the locked DEC-MIL-005 flow without inventing MOS maps.",
    whenToUse: "When working transitioning talent, employer/host opportunities, or pathway windows.",
    whoUsesIt: "Military Talent Partner, plus overlapping Recruiter / Senior Talent Partner military permissions.",
    accessRequired: ["military.read"],
    screenOverview: [
      { href: "/app/military", label: "Military Talent" },
      { href: "/app/military/candidates", label: "Transitioning Talent" },
      { href: "/app/military/opportunities", label: "Employer Opportunities" },
      { href: "/app/military/skillbridge", label: "Pathway operations" },
    ],
    stepByStep: [
      "PierOne is the intermediary, generally not the SkillBridge host.",
      "Transition Talent Profile is an overlay on the existing candidate (physical table skillbridge_profiles).",
      "SkillBridge is a pathway/opportunity type — not a sixth launch service and not a PierOne-owned program.",
      "There is no /app/military/candidates/[id] or /app/military/opportunities/[id] — person is /app/talent/[id]; match work is /app/military/skillbridge/[id].",
      "Cite playbooks/military-transition-pathway.md and playbooks/military-talent-opportunity-assessment.md.",
    ],
    scoutCommands: ["SEARCH", "SHOW_DASHBOARD", "FIND_MATCHES", "SHOW_RECORD", "DRAFT"],
    approvalRequirements: "Military mapping drafts need human review (military.review). Employer briefs are reviewable prose.",
    relatedSlugs: ["military-talent", "playbook-military-transition-pathway"],
    commonMistakes: [
      "Calling the bundle Military Talent Specialist.",
      "Duplicating a candidate per employer.",
      "Inventing MOS-to-civilian maps in chat.",
    ],
    troubleshooting: ["Pathway operations is not a SkillBridge program dashboard."],
  }),
  article({
    slug: "module-projects",
    title: "Delivery projects",
    section: "user-manual",
    summary: "Consulting delivery after an executed contract. Not a search project.",
    sources: ["docs/business/playbooks/project-delivery-closeout.md"],
    contextualRoutes: ["/app/projects"],
    purpose: "Deliver assessment and fractional work on a project, not on a job requisition.",
    whenToUse: "After contract execution (unless an audited Managing Partner override).",
    whoUsesIt: "Operations, Senior Talent Partner, Workforce Consultant.",
    accessRequired: ["projects.read"],
    screenOverview: [
      { href: "/app/projects", label: "Projects" },
      { href: "/app/projects/deliverables", label: "Deliverables" },
    ],
    fields: [
      { name: "name", notes: "List column Project." },
      { name: "status", notes: "List column Status." },
      { name: "health", notes: "List column Health." },
    ],
    stepByStep: [
      "Create from an approved solution, service workflow, and executed contract.",
      "Professional Search execution still uses Jobs — do not confuse the two.",
      "Cite playbooks/project-delivery-closeout.md.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "SHOW_RECORD", "CREATE_TASK", "ASSIGN"],
    approvalRequirements: "Client-facing deliverables need deliverables.approve.",
    relatedSlugs: ["projects", "workforce-consulting"],
    commonMistakes: ["Using a delivery project as a recruiting search project."],
    troubleshooting: ["No create path? Contract is not executed."],
  }),
  article({
    slug: "module-finance",
    title: "Finance screens",
    section: "user-manual",
    summary: "Billing, invoices, AR, and revenue events from stored contracts.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    contextualRoutes: ["/app/finance"],
    purpose: "Operate PierOne billing in WorkforceOS. QuickBooks remains the accounting ledger.",
    whenToUse: "After contract terms or placement fees create stored billing events.",
    whoUsesIt: "Operations, Administrator / Executive, Senior Talent Partner with finance.read.",
    accessRequired: ["finance.read"],
    screenOverview: [
      { href: "/app/finance", label: "Finance" },
      { href: "/app/finance/invoices", label: "Invoices" },
      { href: "/app/finance/ar", label: "AR" },
    ],
    stepByStep: [
      "Amounts come from stored contracts — never invent them.",
      "There is no /app/finance/invoices/[id] — work the invoice list.",
      "QuickBooks posting is off until Phase I.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD"],
    approvalRequirements: "Invoice writes and finance.approve are tighter than read. Scout cannot post AR.",
    relatedSlugs: ["finance", "contracts"],
    commonMistakes: ["Treating WorkforceOS as the general ledger."],
    troubleshooting: ["Recruiters do not own finance."],
  }),
  article({
    slug: "module-admin-people",
    title: "Admin People",
    section: "user-manual",
    summary: "Invite people, set display title, assign access bundles and overrides.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    contextualRoutes: ["/app/admin/users"],
    purpose: "Administer identity and access. Title ≠ Access.",
    whenToUse: "When inviting an operator or changing what they can open.",
    whoUsesIt: "Administrators with admin.users (bundle assignment also needs admin.roles).",
    accessRequired: ["admin.users"],
    screenOverview: [
      { href: "/app/admin/users", label: "People" },
      { href: "/app/admin/roles", label: "Access bundles" },
    ],
    fields: [
      { name: "fullName", notes: "List column Name." },
      { name: "organizationalTitle", notes: "List column Title. Display only." },
      { name: "email", notes: "List column Email." },
    ],
    stepByStep: [
      "Invite from People. Public sign-up is restricted.",
      "Assign one or more access bundles on the person detail. Optionally set grant/deny overrides.",
      "Disabled local users are rejected even if a Clerk session exists.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD"],
    approvalRequirements: "admin.roles to change bundles. Training completion does not assign bundles.",
    relatedSlugs: ["access-quick-start", "admin"],
    commonMistakes: ["Using title as the permission source."],
    troubleshooting: ["Strategy & Technology can assign bundles except Managing Partner. Operations cannot change bundles."],
  }),
  article({
    slug: "module-scout",
    title: "Scout module",
    section: "user-manual",
    summary: "Closed commands, approved knowledge, no SQL, send denied.",
    sources: ["docs/decisions/DECISION_LOG.md"],
    contextualRoutes: ["/app"],
    purpose: "Use Scout as the official assistant without treating chat as the system of record.",
    whenToUse: "When you need to search, summarize, or draft against stored records.",
    whoUsesIt: "Operators with scout.use.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app/academy", label: "Help & Training (Academy)" }],
    stepByStep: [
      "Tooltip: Open Scout. Commands: SEARCH, SUMMARIZE, DRAFT, CREATE, UPDATE, ASSIGN, ADD_TO_POOL, ADD_TO_JOB, CREATE_TASK, CREATE_FOLLOW_UP, SHOW_RECORD, SHOW_DASHBOARD, FIND_MATCHES.",
      "Procedural answers must come from approved knowledge / Academy. Link /app/academy/[slug].",
      "Never generate SQL. Never put email, phone, compensation, or resume into a prompt.",
      "External send is hard-denied (DEC-AI-003 / DEC-AI-009).",
    ],
    scoutCommands: ALL_SCOUT,
    approvalRequirements: "Material writes confirm. Drafts stay Draft → Human Review → Send/Copy. Humans send.",
    relatedSlugs: ["scout", "ai-use-human-review"],
    commonMistakes: ["Asking Scout to RUN_SQL or send a client email."],
    troubleshooting: ["Unknown command tokens are rejected. Rephrase as a registered family."],
  }),
  playbookArticle({
    slug: "playbook-professional-search",
    title: "Professional Search playbook",
    file: "professional-search.md",
    summary: "Launch service professional-search. Public alias Professional & Technical Search.",
    screens: [{ href: "/app/jobs", label: "Jobs" }, { href: "/app/talent", label: "Candidates" }],
    accessRequired: ["jobs.read"],
    relatedSlugs: ["recruiting-hiring", "operating-model"],
  }),
  playbookArticle({
    slug: "playbook-military-talent-opportunity-assessment",
    title: "Military Talent Opportunity Assessment playbook",
    file: "military-talent-opportunity-assessment.md",
    summary: "Launch service military-talent-opportunity-assessment. SkillBridge is a pathway type inside this practice.",
    screens: [{ href: "/app/military", label: "Military Talent" }, { href: "/app/discovery", label: "Discovery" }],
    accessRequired: ["military.read"],
    relatedSlugs: ["military-talent", "playbook-military-transition-pathway"],
  }),
  playbookArticle({
    slug: "playbook-ta-performance-assessment",
    title: "Talent Acquisition Performance Assessment playbook",
    file: "talent-acquisition-performance-assessment.md",
    summary: "Launch service ta-performance-assessment.",
    screens: [{ href: "/app/workforce", label: "Workforce planning" }, { href: "/app/projects", label: "Projects" }],
    accessRequired: ["projects.read"],
    relatedSlugs: ["workforce-consulting", "projects"],
  }),
  playbookArticle({
    slug: "playbook-fractional-talent-partner",
    title: "Fractional Talent Partner playbook",
    file: "fractional-talent-partner.md",
    summary: "Launch service fractional-talent-partner. Scope is never unlimited recruiting.",
    screens: [{ href: "/app/projects", label: "Projects" }, { href: "/app/solutions", label: "Solution Plans" }],
    accessRequired: ["projects.read"],
    relatedSlugs: ["projects", "operating-model"],
  }),
  playbookArticle({
    slug: "playbook-workforce-pipeline-assessment",
    title: "Workforce Pipeline Assessment playbook",
    file: "workforce-pipeline-assessment.md",
    summary: "Launch service workforce-pipeline-assessment. Client-facing plans need human approval.",
    screens: [{ href: "/app/workforce", label: "Workforce planning" }, { href: "/app/projects", label: "Projects" }],
    accessRequired: ["workforce.read"],
    relatedSlugs: ["workforce-consulting"],
  }),
  playbookArticle({
    slug: "playbook-military-transition-pathway",
    title: "Military Transition / SkillBridge-eligible operations",
    file: "military-transition-pathway.md",
    summary: "Internal pathway ops — not a sixth client offer.",
    screens: [{ href: "/app/military/skillbridge", label: "Pathway operations" }],
    accessRequired: ["skillbridge.read"],
    relatedSlugs: ["military-talent", "module-military"],
  }),
  playbookArticle({
    slug: "playbook-recruiting-and-hiring",
    title: "Recruiting & Hiring playbook",
    file: "recruiting-and-hiring.md",
    summary: "Shared search execution on Jobs and the Talent Network.",
    screens: [{ href: "/app/jobs", label: "Jobs" }, { href: "/app/recruiting/applications", label: "Applications" }],
    accessRequired: ["jobs.read"],
    relatedSlugs: ["recruiting-hiring", "module-jobs"],
  }),
  playbookArticle({
    slug: "playbook-client-discovery",
    title: "Client Discovery playbook",
    file: "client-discovery.md",
    summary: "Shared commercial intake.",
    screens: [{ href: "/app/discovery", label: "Discovery" }],
    accessRequired: ["discovery.read"],
    relatedSlugs: ["module-discovery"],
  }),
  playbookArticle({
    slug: "playbook-proposal-contract-handoff",
    title: "Proposal / Contract Handoff playbook",
    file: "proposal-contract-handoff.md",
    summary: "Shared commercial close. Legal packages stay on the engagement.",
    screens: [{ href: "/app/proposals", label: "Proposals" }, { href: "/app/contracts", label: "Contracts" }],
    accessRequired: ["proposals.read"],
    relatedSlugs: ["proposals", "contracts"],
  }),
  playbookArticle({
    slug: "playbook-project-delivery-closeout",
    title: "Project Delivery / Closeout playbook",
    file: "project-delivery-closeout.md",
    summary: "Shared delivery and expansion. No /app/expansion route.",
    screens: [{ href: "/app/projects", label: "Projects" }],
    accessRequired: ["projects.read"],
    relatedSlugs: ["projects", "module-projects"],
  }),
  article({
    slug: "recruiting-hiring",
    title: "Recruiting & Hiring",
    section: "recruiting-hiring",
    summary: "Job → hire on the Talent Network. One candidate record.",
    sources: ["docs/business/playbooks/recruiting-and-hiring.md", "docs/business/PIERONE_OPERATING_MANUAL.md"],
    isTrainingModule: true,
    requiredIfAny: ["jobs.write", "applications.read", "candidates.write"],
    purpose: "Train operators who execute search and hiring.",
    whenToUse: "When your effective access includes recruiting execution permissions.",
    whoUsesIt: "Recruiter Standard and Senior Talent Partner.",
    accessRequired: ["jobs.read"],
    screenOverview: [
      { href: "/app/jobs", label: "Jobs" },
      { href: "/app/talent", label: "Candidates" },
      { href: "/app/recruiting/applications", label: "Applications" },
      { href: "/app/submissions", label: "Submissions" },
      { href: "/app/onboarding", label: "Onboarding (candidate / new-hire, not Phase H employee cadence)" },
    ],
    stepByStep: [
      "Follow the recruiting flow in PIERONE_OPERATING_MANUAL.md and playbooks/recruiting-and-hiring.md.",
      "Internal Talent Network search before external sourcing.",
      "Material rejection and client submission need a human. Scout cannot reject with source=scout.",
    ],
    scoutCommands: ["SEARCH", "FIND_MATCHES", "ADD_TO_JOB", "DRAFT"],
    approvalRequirements: "submissions.approve, offers.approve, applications.reject are human gates.",
    relatedSlugs: ["module-jobs", "module-talent", "playbook-professional-search"],
    commonMistakes: ["Duplicating candidates.", "Using /app/onboarding as PierOne employee Academy onboarding."],
    troubleshooting: ["No /app/screening or /app/matching — use application detail, workbench, and job pipeline."],
  }),
  article({
    slug: "military-talent",
    title: "Military Talent",
    section: "military-talent",
    summary: "Intermediary model. Transition Talent Profile. SkillBridge-eligible pathway. Military Talent Partner.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/workflows/SERVICE_WORKFLOWS.md"],
    isTrainingModule: true,
    requiredIfAny: ["military.read", "skillbridge.read"],
    purpose: "Lock the military operating model for anyone with military or pathway access.",
    whenToUse: "When your effective access includes military.read or skillbridge.read.",
    whoUsesIt: "Military Talent Partner and overlapping talent/recruiter military access.",
    accessRequired: ["military.read"],
    screenOverview: [
      { href: "/app/military", label: "Military Talent" },
      { href: "/app/military/skillbridge", label: "Pathway operations" },
    ],
    stepByStep: [
      "Five services only. Pathway ops is not a sixth offer.",
      "Do not invent military-mapping rules. Use stored, reviewed mappings.",
      "Operator bundle name is Military Talent Partner.",
    ],
    scoutCommands: ["SEARCH", "SHOW_DASHBOARD", "FIND_MATCHES", "DRAFT"],
    approvalRequirements: "Mapping review and employer briefs need a human. Scout drafts do not send.",
    relatedSlugs: ["module-military", "playbook-military-transition-pathway"],
    commonMistakes: ["SkillBridge host assumption.", "Specialist language in new copy."],
    troubleshooting: ["Join the network without a current opening. A public job posting is not required first."],
  }),
  article({
    slug: "workforce-consulting",
    title: "Workforce Consulting",
    section: "workforce-consulting",
    summary: "TA Performance, Fractional, and Workforce Pipeline delivery on projects.",
    sources: [
      "docs/business/playbooks/talent-acquisition-performance-assessment.md",
      "docs/business/playbooks/workforce-pipeline-assessment.md",
      "docs/business/playbooks/fractional-talent-partner.md",
    ],
    isTrainingModule: true,
    requiredIfAny: ["workforce.write", "workforce.analyze"],
    purpose: "Train consultants who write or analyze workforce plans.",
    whenToUse: "When your effective access includes workforce.write or workforce.analyze.",
    whoUsesIt: "Workforce Consultant and overlapping delivery owners.",
    accessRequired: ["workforce.read"],
    screenOverview: [
      { href: "/app/workforce", label: "Workforce planning" },
      { href: "/app/projects", label: "Projects" },
    ],
    stepByStep: [
      "Execute on delivery projects, not as unlimited recruiting.",
      "Client-facing Workforce Pipeline Plans need workforce.approve.",
      "Cite the three assessment/fractional playbooks — do not invent a new offer.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "DRAFT"],
    approvalRequirements: "workforce.approve and deliverables.approve for client-facing work.",
    relatedSlugs: ["projects", "playbook-workforce-pipeline-assessment"],
    commonMistakes: ["Selling temp staffing or payroll out of a workforce project."],
    troubleshooting: ["Assessments live under /app/workforce/assessments/[assessmentId]."],
  }),
  article({
    slug: "projects",
    title: "Projects",
    section: "projects",
    summary: "Delivery after contract. Search projects stay under Jobs.",
    sources: ["docs/business/playbooks/project-delivery-closeout.md"],
    isTrainingModule: true,
    requiredIfAny: ["projects.write"],
    purpose: "Train operators who create or run delivery projects.",
    whenToUse: "When your effective access includes projects.write.",
    whoUsesIt: "Operations, Senior Talent Partner, Workforce Consultant.",
    accessRequired: ["projects.write"],
    screenOverview: [{ href: "/app/projects", label: "Projects" }],
    stepByStep: [
      "Cite playbooks/project-delivery-closeout.md.",
      "Legal packages stay on the engagement.",
      "Expansion is a new opportunity on the company — not a sixth service.",
    ],
    scoutCommands: ["SEARCH", "SUMMARIZE", "CREATE_TASK", "ASSIGN"],
    approvalRequirements: "Contract rule before create. Deliverable approval before client send.",
    relatedSlugs: ["module-projects", "contracts"],
    commonMistakes: ["Starting delivery without an executed contract."],
    troubleshooting: ["Recruiters may read projects without being assigned this training."],
  }),
  article({
    slug: "proposals",
    title: "Proposals",
    section: "proposals",
    summary: "Approved solution → internal review → human send.",
    sources: ["docs/business/playbooks/proposal-contract-handoff.md"],
    isTrainingModule: true,
    requiredIfAny: ["proposals.write"],
    purpose: "Train operators who write proposals.",
    whenToUse: "When your effective access includes proposals.write.",
    whoUsesIt: "Senior Talent Partner, Workforce Consultant, Operations.",
    accessRequired: ["proposals.write"],
    screenOverview: [{ href: "/app/proposals", label: "Proposals" }],
    stepByStep: ["Cite playbooks/proposal-contract-handoff.md. Scout cannot send."],
    scoutCommands: ["SEARCH", "SUMMARIZE", "DRAFT"],
    approvalRequirements: "proposals.approve. Material AI proposal language goes to the Review Queue.",
    relatedSlugs: ["module-proposals", "contracts", "ai-use-human-review"],
    commonMistakes: ["Sending before internal_review."],
    troubleshooting: ["Recruiter Standard can read proposals without this required module."],
  }),
  article({
    slug: "contracts",
    title: "Contracts",
    section: "contracts",
    summary: "Legal packages belong on the engagement. Live DocuSign is Phase I.",
    sources: ["docs/business/playbooks/proposal-contract-handoff.md"],
    isTrainingModule: true,
    requiredIfAny: ["contracts.write"],
    purpose: "Train operators who write or execute contracts.",
    whenToUse: "When your effective access includes contracts.write.",
    whoUsesIt: "Operations, Senior Talent Partner, Administrator / Executive.",
    accessRequired: ["contracts.write"],
    screenOverview: [
      { href: "/app/contracts", label: "Contracts" },
      { href: "/app/legal/templates", label: "Legal templates" },
    ],
    stepByStep: [
      "Packages link to the service/engagement. Not a free-standing legal product.",
      "Record execution in WorkforceOS until DocuSign is live.",
      "Scout cannot execute or send contracts.",
    ],
    scoutCommands: ["SEARCH", "SHOW_RECORD"],
    approvalRequirements: "contracts.approve / execute is a human gate.",
    relatedSlugs: ["proposals", "finance"],
    commonMistakes: ["Labeling a template attorney-approved unless attorney_approved is stored."],
    troubleshooting: ["/app/legal index redirects to contracts."],
  }),
  article({
    slug: "finance",
    title: "Finance",
    section: "finance",
    summary: "Stored billing and AR. Not payroll, GL, tax, or AP.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    isTrainingModule: true,
    requiredIfAny: ["finance.read", "invoices.read"],
    purpose: "Train operators who can see operating finance.",
    whenToUse: "When your effective access includes finance.read or invoices.read.",
    whoUsesIt: "Operations, Administrator / Executive, Senior Talent Partner.",
    accessRequired: ["finance.read"],
    screenOverview: [{ href: "/app/finance", label: "Finance" }],
    stepByStep: [
      "WorkforceOS owns schedules, invoice expectations, AR, and revenue events.",
      "QuickBooks remains the ledger. Posting is off until Phase I.",
      "Never invent amounts. Recruiter Standard does not own finance.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "finance.approve for privileged writes. Scout cannot post AR.",
    relatedSlugs: ["module-finance", "contracts"],
    commonMistakes: ["Using finance screens as a general ledger."],
    troubleshooting: ["Missing Finance nav? You lack finance.read / billing.read."],
  }),
  article({
    slug: "scout",
    title: "Scout",
    section: "scout",
    summary: "Official assistant. Closed registry. Send denied. Academy links for how-to.",
    sources: ["docs/decisions/DECISION_LOG.md"],
    isTrainingModule: true,
    requiredIfAny: ["scout.use"],
    purpose: "Train every Scout user on allowed commands and PII rules.",
    whenToUse: "If you have scout.use — which is on the standard bundles.",
    whoUsesIt: "Signed-in operators.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app/academy/module-scout", label: "Scout module article" }],
    stepByStep: [
      "DEC-AI-009 / DEC-AI-010: closed commands, RBAC and PII strip before model context.",
      "Procedural answers cite Academy URLs in the form /app/academy/[slug].",
      "isScoutExternalSendEnabled() is false. Do not enable send in this phase.",
    ],
    scoutCommands: ALL_SCOUT,
    approvalRequirements: "Confirmation for material writes. Humans send.",
    relatedSlugs: ["module-scout", "ai-use-human-review"],
    commonMistakes: ["Treating Scout chat as the system of record."],
    troubleshooting: ["No Scout button? You lack scout.use."],
  }),
  article({
    slug: "ai-use-human-review",
    title: "AI use and human review",
    section: "ai-use",
    summary: "Agents draft. Humans approve material output. Review Queue is the surface.",
    sources: ["docs/decisions/DECISION_LOG.md"],
    isTrainingModule: true,
    requiredIfAny: ["scout.draft", "agents.read"],
    purpose: "Train people who draft with Scout or see the Review Queue.",
    whenToUse: "When your effective access includes scout.draft or agents.read.",
    whoUsesIt: "Recruiters who draft, talent partners, and AI reviewers — not a cost-admin course.",
    accessRequired: ["scout.draft"],
    screenOverview: [{ href: "/app/ai-operations/review", label: "Review Queue" }],
    stepByStep: [
      "DEC-AI-001 / DEC-AI-008: material outputs need provenance and a human. Agents cannot approve themselves.",
      "Draft → Human Review → Send/Copy. Never auto-send.",
      "This is not AI-cost training. Cost consoles stay behind agents.manage.",
    ],
    scoutCommands: ["DRAFT", "SUMMARIZE"],
    approvalRequirements: "Review Queue decisions are human. The originating agent cannot decide.",
    relatedSlugs: ["ai-cost-admin", "scout"],
    commonMistakes: ["Letting a draft leave the firm without a human."],
    troubleshooting: ["Recruiters should not see /app/ai-operations cost admin."],
  }),
  article({
    slug: "ai-cost-admin",
    title: "AI cost and administration",
    section: "ai-use",
    summary: "Spend, health, prompts, and knowledge sources. agents.manage only.",
    sources: ["docs/decisions/DECISION_LOG.md"],
    isTrainingModule: true,
    requiredIfAny: ["agents.manage"],
    purpose: "Train AI administrators. Recruiters must not receive this as required training.",
    whenToUse: "Only when your effective access includes agents.manage.",
    whoUsesIt: "Strategy & Technology Administrator and Managing Partner.",
    accessRequired: ["agents.manage"],
    screenOverview: [
      { href: "/app/ai-operations", label: "AI administration" },
      { href: "/app/admin/system-health", label: "System status" },
    ],
    stepByStep: [
      "Costs and model health are admin work. Recruiter bundles do not include agents.manage.",
      "Knowledge records stay approved and ACL-filtered (DEC-AI-006).",
      "Completing this module does not grant agents.manage.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "Prompt versions are immutable once approved (DEC-AI-004).",
    relatedSlugs: ["ai-use-human-review", "admin"],
    commonMistakes: ["Opening AI costs to Recruiter Standard."],
    troubleshooting: ["LIVE vs HEURISTIC is labeled on System Health. Do not print secrets."],
  }),
  article({
    slug: "security-candidate-privacy",
    title: "Security and candidate privacy",
    section: "security",
    summary: "Restricted PII, server-side authz, no secrets in the client.",
    sources: [".cursor/rules/security.mdc", "docs/decisions/DECISION_LOG.md"],
    isTrainingModule: true,
    requiredIfAny: [],
    purpose: "State operator rules for candidate data and authorization.",
    whenToUse: "Before you open Talent, Military, or export anything.",
    whoUsesIt: "Every employee.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app/talent", label: "Candidates" }],
    stepByStep: [
      "Candidate data is Restricted PII. Access requires candidate_pii.read — not candidates.read alone.",
      "Scout and SkillBridge obey the same rule: strip email/phone/compensation/resume before model context.",
      "UI hiding is not security. Authorization is enforced server-side.",
      "Do not store founder ownership or cap-table information.",
      "DEC-SEC-001: WorkforceOS is internal-first.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "privacy.delete is a controlled process, distinct from archive. PII export is elevated.",
    relatedSlugs: ["module-talent", "access-quick-start"],
    commonMistakes: ["Pasting a resume into Scout.", "Using Clerk metadata as the permission source."],
    troubleshooting: ["Disabled local users must be rejected even if Clerk is signed in."],
  }),
  article({
    slug: "admin",
    title: "Admin",
    section: "admin",
    summary: "People, bundles, access review, and connected tools.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md"],
    isTrainingModule: true,
    requiredIfAny: ["admin.users", "admin.roles"],
    purpose: "Train people administrators. Title ≠ Access.",
    whenToUse: "When your effective access includes admin.users or admin.roles.",
    whoUsesIt: "Operations (people, not bundles), Strategy & Technology, Managing Partner.",
    accessRequired: ["admin.users"],
    screenOverview: [
      { href: "/app/admin/users", label: "People" },
      { href: "/app/admin/roles", label: "Access bundles" },
      { href: "/app/admin/access-review", label: "Access review" },
    ],
    stepByStep: [
      "Invite-only. Assign bundles and optional overrides on the person detail.",
      "Operations cannot change access bundles.",
      "Do not grant recruiters agents.manage.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "Access changes are admin actions. Academy completion is not.",
    relatedSlugs: ["module-admin-people", "access-quick-start"],
    commonMistakes: ["Equating organizational title with an access bundle."],
    troubleshooting: ["Access review lists sensitive permissions and stale accounts."],
  }),
  article({
    slug: "faqs",
    title: "FAQs",
    section: "faqs",
    summary: "Short answers from approved decisions — not a second manual.",
    sources: ["docs/business/PIERONE_OPERATING_MANUAL.md", "docs/decisions/DECISION_LOG.md"],
    purpose: "Answer recurring operator questions with citations.",
    whenToUse: "When you are stuck on naming, access, Scout, or military language.",
    whoUsesIt: "Every employee.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app/academy", label: "Help & Training" }],
    stepByStep: [
      "Is title access? No. DEC-AUTH-002.",
      "Can Scout send email? No. External send is hard-denied until Phase I.",
      "Is SkillBridge a sixth service? No. It is a pathway type.",
      "Does finishing training raise permissions? No.",
      "Where do new PierOne employees onboard? /app/academy/onboarding and People. /app/onboarding is the ATS hire queue.",
      "Can I write SQL in Scout? No.",
      "Where are playbooks? docs/business/SERVICE_PLAYBOOKS.md and the Service Delivery Playbooks section here.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "None.",
    relatedSlugs: ["getting-started", "employee-onboarding", "operating-model"],
    commonMistakes: ["Using FAQs instead of the playbook when delivering a service."],
    troubleshooting: ["Ask Scout for an Academy article if you have scout.use."],
  }),
  article({
    slug: "release-notes",
    title: "Release notes",
    section: "release-notes",
    summary: "Operator-facing excerpt. Full history is docs/CHANGELOG.md. No secrets.",
    sources: ["docs/CHANGELOG.md"],
    purpose: "Point at the changelog without dumping environment values.",
    whenToUse: "After a release, to see what operators should learn.",
    whoUsesIt: "Every employee.",
    accessRequired: ["scout.use"],
    screenOverview: [{ href: "/app/academy", label: "Help & Training" }],
    stepByStep: [
      "Unreleased work is listed in docs/CHANGELOG.md. Do not copy API keys, connection strings, or Clerk secrets into Academy.",
      "Phase E added this Academy. Training is by effective access. Completion does not grant permissions.",
      "Phase H added PierOne staff onboarding at /app/academy/onboarding. It is not the ATS hire path.",
      "Scout send remains denied.",
    ],
    scoutCommands: ["SEARCH"],
    approvalRequirements: "None.",
    relatedSlugs: ["getting-started"],
    commonMistakes: ["Pasting Vercel or Neon secret values into release notes."],
    troubleshooting: ["Engineering deploy notes stay in docs/operations/WORKFORCEOS_OPERATING_PLAYBOOK.md."],
  }),
];

const BY_SLUG = new Map(ACADEMY_ARTICLES.map((item) => [item.slug, item]));

export function getAcademyArticle(slug: string) {
  return BY_SLUG.get(slug) ?? null;
}

export function academySections() {
  const grouped = new Map<AcademySectionId, AcademyArticle[]>();
  for (const item of ACADEMY_ARTICLES) {
    const list = grouped.get(item.section) ?? [];
    list.push(item);
    grouped.set(item.section, list);
  }
  return grouped;
}

export function articleForRoute(pathname: string) {
  const exact = ACADEMY_ARTICLES.find((item) => item.contextualRoutes?.includes(pathname));
  if (exact) return exact;
  return (
    ACADEMY_ARTICLES.find((item) =>
      item.contextualRoutes?.some((route) => route !== "/app" && pathname.startsWith(route)),
    ) ?? null
  );
}

export function searchAcademyArticles(query: string) {
  const needle = query.trim().toLowerCase();
  if (!needle) return ACADEMY_ARTICLES.slice(0, 12);
  return ACADEMY_ARTICLES.filter((item) => {
    const hay = [
      item.slug,
      item.title,
      item.summary,
      item.purpose,
      item.section,
      ...item.sources,
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(needle);
  }).slice(0, 12);
}
